sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    bucket-name: sky-take-out-daoge
    endpoint: oss-cn-beijing.aliyuncs.com
    #储存在环境变量中
    access-key-secret: ${ALI_OSS_ACCESS_KEY_SECRET}
    access-key-id: ${ALI_OSS_ACCESS_KEY_ID}
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    #储存在环境变量中
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}